### ISSUE TITLE
Can't ssh 

### ISSUE THREAD

**Issue by FarazzShaikh** [faf0/macos-qemu-rpi#2]
Hello,

I cannot seem to get ssh to work. I have installed and ran it, it even gives me the pi console but i cannot ssh from my host mac into the pi. This is the output of my ssh command
```sh
> ssh -v -o "PreferredAuthentications password" -o "PasswordAuthentication yes" -p 5022 pi@localhost
OpenSSH_8.1p1, LibreSSL 2.7.3
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 47: Applying options for *
debug1: Connecting to localhost port 5022.
debug1: Connection established.
debug1: identity file /Users/farazshaikh/.ssh/id_rsa type 0
debug1: identity file /Users/farazshaikh/.ssh/id_rsa-cert type -1
debug1: identity file /Users/farazshaikh/.ssh/id_dsa type -1
debug1: identity file /Users/farazshaikh/.ssh/id_dsa-cert type -1
debug1: identity file /Users/farazshaikh/.ssh/id_ecdsa type -1
debug1: identity file /Users/farazshaikh/.ssh/id_ecdsa-cert type -1
debug1: identity file /Users/farazshaikh/.ssh/id_ed25519 type 3
debug1: identity file /Users/farazshaikh/.ssh/id_ed25519-cert type -1
debug1: identity file /Users/farazshaikh/.ssh/id_xmss type -1
debug1: identity file /Users/farazshaikh/.ssh/id_xmss-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.1
kex_exchange_identification: read: Connection reset by peer
```

**Comment by faf0** [comment]
Hi @FarazzShaikh , did you try the command with the `-F /dev/null` option?
This option will have ssh ignore your config files.

It looks like ssh is reading a config file and applying options, and then iterating over your keys for public key authentication:
```
/etc/ssh/ssh_config line 47: Applying options for *
[...]
debug1: identity file /Users/farazshaikh/.ssh/id_rsa type 0
[...]
debug1: identity file /Users/farazshaikh/.ssh/id_dsa type -1
[...]
```

**Comment by FarazzShaikh** [comment]
Hello @faf0, Yes that along with restarting ssh on the Pi worked. However I am not able to access the internet and use `apt-get` or `ping` anything. Is there a way to have network access on the Pi VM?

**Comment by faf0** [comment]
Regarding network connectivity to the Internet via your host, the following line should provide that:
https://github.com/faf0/macos-qemu-rpi/blob/4e9038b6aa67913b02e60d301f6a328364f87e04/run.sh#L29

If it doesn't work, you may try other options as documented under https://wiki.qemu.org/Documentation/Networking#The_-nic_option such as the following:
```
 -netdev user,id=mynet0 -device sungem,netdev=mynet0
```

**Comment by FarazzShaikh** [comment]
Well looks like internet is connected now, trying to curl a file works, but `sudo apt install git` returns `404  Not Found` and `Failed to fetch`, any idea?. Thanks for helping out, really appreciate it.
