### ISSUE TITLE
qemu-system-aarch64: Invalid SD card size: 1.72 GiB

### ISSUE THREAD

**Issue by marceloch2** [faf0/macos-qemu-rpi#4]
Hi, just runned install.sh and after run.sh and getting this error bellow.

qemu-system-aarch64: Invalid SD card size: 1.72 GiB

Not sure where to change the size or where it's set, thanks in advance.

**Comment by faf0** [comment]
Hi @marceloch2 , the error might be related to not running the resize command: https://github.com/faf0/macos-qemu-rpi/issues/3#issuecomment-804036672
Newer versions of the script should already take care of that, though.

**Comment by marceloch2** [comment]
Thanks @faf0 , running the command to resize works and now the run script went well. Thanks again for your time.
